# Generated by Django 2.2.19 on 2021-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20211018_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
