# Generated by Django 2.2.16 on 2021-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20211127_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату', verbose_name='Дата публикации'),
        ),
    ]
